name: kthcloud-ci
"on":
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                registry: registry.cloud.cbh.kth.se
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and push
              uses: hoverkraft-tech/compose-action@v2.3.0
              with:
                push: true
                tags: ${{ secrets.DOCKER_TAG }}
                up-flags: "--build"
